---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - gnupg
      - ca-certificates
      - apt-transport-https
      - apache2-utils
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags: adguard

- name: Create system group
  ansible.builtin.group:
    name: "{{ adguard_system_group }}"
    system: true
    state: present
  become: true
  tags: adguard

- name: Create system user
  ansible.builtin.user:
    name: "{{ adguard_system_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ adguard_system_group }}"
    createhome: false
  become: true
  tags: adguard

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adguard_system_user }}"
    group: "{{ adguard_system_group }}"
    mode: "0755"
  with_items:
    - "{{ adguard_config_dir }}"
    - "{{ adguard_db_dir }}"
  become: true
  tags: adguard

- name: Check if is installed
  ansible.builtin.stat:
    path: "{{ adguard_binary_install_dir }}/adguard"
  register: __adguard_is_installed
  become: true
  tags: adguard

- name: Gather currently installed version (if any)
  ansible.builtin.command: "{{ adguard_binary_install_dir }}/adguard --version"
  changed_when: false
  register: __adguard_current_version_output
  when: __adguard_is_installed.stat.exists
  become: true
  tags: adguard

- name: "Set installed adguard version to {{ __adguard_current_version_output.stdout_lines[0].split(' ')[3][1:] }}"
  ansible.builtin.set_fact:
    adguard_installed_version:  "{{ __adguard_current_version_output.stdout_lines[0].split(' ')[3][1:] }}"
  when: __adguard_is_installed.stat.exists
  tags: adguard

- name: Get latest release
  ansible.builtin.uri:
    url: "https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest"
    method: GET
    return_content: true
    status_code: "200"
    body_format: json
    validate_certs: false
    user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
    password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
  environment: "{{ proxy_env }}"
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  register: _latest_release
  until: _latest_release.status == 200
  retries: 5
  become: true
  tags: adguard
  when: adguard_version == "latest"

- name: "Set version to {{ _latest_release.json.tag_name[1:] }}"
  ansible.builtin.set_fact:
    adguard_version: "{{ _latest_release.json.tag_name[1:] }}"
  become: true
  tags: adguard
  when: adguard_version == "latest"


- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: adguard
  register: adguard_local_tempdir
  tags: adguard
  when: (not __adguard_is_installed.stat.exists) or (adguard_installed_version != adguard_version)

- name: Download binary 
  ansible.builtin.get_url:
    url: "https://github.com/AdguardTeam/AdGuardHome/releases/download/v{{ adguard_version }}/AdGuardHome_linux_{{ go_arch }}.tar.gz"
    dest: "{{ adguard_local_tempdir.path }}/adguard-{{ adguard_version }}.linux-{{ go_arch }}.tar.gz"
    owner: "{{ adguard_system_user }}"
    group: "{{ adguard_system_group }}"
    mode: "0755"
  environment: "{{ proxy_env }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  # run_once: true # <-- this can't be set due to multi-arch support
  check_mode: false
  tags: adguard
  when: (not __adguard_is_installed.stat.exists) or (adguard_installed_version != adguard_version)

- name: Unpack binaries
  ansible.builtin.unarchive:
    src: "{{ adguard_local_tempdir.path }}/adguard-{{ adguard_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "{{ adguard_local_tempdir.path }}"
    remote_src: yes
  check_mode: false
  tags: adguard
  when: (not __adguard_is_installed.stat.exists) or (adguard_installed_version != adguard_version)

- name: Propagate binaries
  ansible.builtin.copy:
    src: "{{ adguard_local_tempdir.path }}/AdGuardHome/AdGuardHome"
    dest: "{{ adguard_binary_install_dir }}/adguard"
    mode: "0755"
    owner: root
    group: root
    remote_src: yes
  notify: Restart adguard
  become: true
  tags: adguard
  when: (not __adguard_is_installed.stat.exists) or (adguard_installed_version != adguard_version)

- name: Remove temporary files
  ansible.builtin.file:
    path: "{{ adguard_local_tempdir.path }}"
    state: absent
  tags: adguard
  when: (not __adguard_is_installed.stat.exists) or (adguard_installed_version != adguard_version)

- name: Copy adguard config
  ansible.builtin.template:
    force: true
    src: config.yaml.j2
    dest: "{{ adguard_config_dir }}/config.yaml"
    owner: "{{ adguard_system_user }}"
    group: "{{ adguard_system_group }}"
    mode: "0644"
    validate: "{{ adguard_binary_install_dir }}/adguard --check-config -c %s"
  notify: Reload adguard
  become: true
  tags:
    - adguard
    - adguard_config

- name: Create systemd service unit
  ansible.builtin.template:
    src: adguard.service.j2
    dest: /etc/systemd/system/adguard.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart adguard
  become: true
  tags:
    - adguard
    - adguard_config

- name: Start and enable adguard service
  ansible.builtin.systemd:
    daemon_reload: true
    name: adguard
    state: started
    enabled: true
  become: true
  tags:
    - adguard
    - adguard_config
