---
- name: Restart adguard
  ansible.builtin.systemd:
    daemon_reload: true
    name: adguard
    state: restarted
  become: true
  tags: adguard

- name: Reload adguard
  ansible.builtin.systemd:
    name: adguard
    state: reloaded
  become: true
  tags: adguard